# Generated by Django 3.0.5 on 2020-04-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sold_to',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('UNSOLD', 'UNSOLD'), ('CLAIMED', 'CLAIMED')], default='UNSOLD', max_length=10),
        ),
    ]
